# Generated by Django 4.2.5 on 2023-10-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_gestao', '0003_rename_name_book_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='livro',
            new_name='book',
        ),
    ]
