# Generated by Django 4.2.5 on 2023-10-13 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255)),
                ('finalizado', models.BooleanField(default=False)),
                ('resenha', models.TextField(max_length=255)),
                ('data', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
